---
- name: Install and Enable NGINX and upload My website
  hosts: all
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure NGINX is running and enabled on boot
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy File to Server
      copy: src={{ source_file }} dest={{destin_file}} mode=0555
      notify: Restart NGINX

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

