---
- name: Install and Enable NGINX
  hosts: all
  become: yes

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure NGINX is running and enabled on boot
      service:
        name: nginx
        state: started
        enabled: yes
