---
- name: Loop Playbook
  hosts: first_server
  become: yes

  tasks:
    - name: Say Hello to All
      debug:
        msg: "Hello {{ item }}"
      loop:
        - "Vasya"
        - "Petya"
        - "Maksim"
        - "Artem"
        - "Masha"

    - name: Ensure file is empty
      file:
        path: myexample.txt
        state: absent

    - name: Loop Until Example
      shell: echo -n Z >> myexample.txt && cat myexample.txt
      register: output
      delay: 2
      retries: 10
      until: '"ZZZZ" in output.stdout'

    - name: Print Final output
      debug:
        var: output.stdout

#    - name: Install many packages
#      apt:
#        name: "{{ item }}"
#        state: present
#      loop:
#        - python
#        - tree
#        - htop
#        - postgresql

